# Generated by Django 2.2 on 2022-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=150)),
                ('contenu', models.TextField(max_length=500)),
            ],
        ),
    ]
